version: '3'

services:
  menu-maestro:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      - ./uploads:/app/uploads
    environment:
      - ENVIRONMENT=container
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - BEDROCK_MODEL_ID=${BEDROCK_MODEL_ID:-us.amazon.nova-pro-v1:0}
      - USE_S3=${USE_S3:-false}
      - S3_BUCKET=${S3_BUCKET:-menu-maestro-images}